Doing lesson 17
TatsianaKazachenka/moodpanda pull request #1
Opened 2021-02-07 15:08 UTC by TatsianaKazachenka

2021-02-07 19:04 UTC, vchesnakoutest requested changes
make fixes and merge to master

2021-02-07 19:04 UTC, vchesnakoutest commented on src/main/java/pages/FeedPage.java
> +    public String textPost() {
getPostText()

2021-02-07 19:04 UTC, vchesnakoutest commented on src/main/java/pages/FeedPage.java
> +    public int moodLevel() {
getMoodLevel()

2021-02-07 19:04 UTC, vchesnakoutest commented on src/main/java/pages/RateYourHappiness.java
> +public class RateYourHappiness {
RateYourHappinessPage

2021-02-07 19:04 UTC, vchesnakoutest commented on src/main/java/steps/MoodUpdateModalSteps.java
> +    public MoodUpdateModal fullingFieldAndGoToDiary(int moodValue, String description) {
updateMoodAndGoToDiary

2021-02-07 19:04 UTC, vchesnakoutest commented on src/test/java/tests/MoodPandaTest.java
> +        int getMoodValue = rateYourHappiness.getMoodValueHappiness();
int moodValue (use 'get' in methods names)

2021-02-07 19:04 UTC, vchesnakoutest commented on src/test/java/tests/MoodPandaTest.java
> +    public void DescriptionTest() {
methods should be named in camelCase: descriptionTest

2021-02-07 19:04 UTC, vchesnakoutest commented on src/test/java/tests/MoodPandaTest.java
> +    public void LevelMoodTest() {
methods should be named in camelCase: levelMoodTest

2021-02-07 19:04 UTC, vchesnakoutest commented on src/test/java/tests/MoodPandaTest.java
> +    @Test(description = "check the number of hugs after clicking")
methods should be named in camelCase: hugTest

2021-02-09 15:13 UTC, TatsianaKazachenka commented on src/main/java/pages/FeedPage.java
> +    public String textPost() {
done

2021-02-09 15:13 UTC, TatsianaKazachenka commented on src/main/java/pages/FeedPage.java
> +    public int moodLevel() {
done

2021-02-09 15:14 UTC, TatsianaKazachenka commented on src/main/java/pages/RateYourHappiness.java
> +public class RateYourHappiness {
done

2021-02-09 15:15 UTC, TatsianaKazachenka commented on src/main/java/steps/MoodUpdateModalSteps.java
> +    public MoodUpdateModal fullingFieldAndGoToDiary(int moodValue, String description) {
done

2021-02-09 15:17 UTC, TatsianaKazachenka commented on src/test/java/tests/MoodPandaTest.java
> +    public void DescriptionTest() {
done

2021-02-09 15:17 UTC, TatsianaKazachenka commented on src/test/java/tests/MoodPandaTest.java
> +    public void LevelMoodTest() {
done

2021-02-09 15:17 UTC, TatsianaKazachenka commented on src/test/java/tests/MoodPandaTest.java
> +    @Test(description = "check the number of hugs after clicking")
done

2021-02-09 15:24 UTC, TatsianaKazachenka commented on src/test/java/tests/MoodPandaTest.java
> +        int getMoodValue = rateYourHappiness.getMoodValueHappiness();
done

2021-02-09 15:26 UTC, merged